import { type Metadata } from "next";
import { LegalLayout } from "~/app/_components/legal-layout";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How EthioClaw collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="May 26, 2026">
      <p>
        EthioClaw (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) operates the EthioClaw platform
        (the &ldquo;Service&rdquo;). This Privacy Policy explains how we collect, use, disclose, and
        safeguard your information when you use our Service.
      </p>

      <h2>Information We Collect</h2>
      <h3>Account Information</h3>
      <p>
        When you create an account, we collect your name, email address, username, and password.
        Passwords are hashed using industry-standard cryptographic functions. We do not store
        plaintext passwords.
      </p>

      <h3>Conversations and Messages</h3>
      <p>
        We store the content of your conversations with EthioClaw, including the messages you send
        and the responses generated by the AI. This is necessary for the Service to function
        &mdash; your agent needs context to remember preferences, handle ongoing tasks, and
        maintain continuity across sessions.
      </p>

      <h3>Tool Usage and Execution Logs</h3>
      <p>
        When EthioClaw connects to third-party services on your behalf (via OAuth), we log the
        tools invoked, their parameters, and execution results. These logs are used for debugging,
        security auditing, and improving tool selection accuracy. We do not log the full content
        of emails, documents, or other data retrieved through tools unless it is required for the
        Service to function.
      </p>

      <h3>OAuth Credentials</h3>
      <p>
        We use OAuth to connect to third-party services such as Gmail, Notion, GitHub, and others.
        We store OAuth access tokens and refresh tokens encrypted at rest. We never store the
        plaintext passwords for any third-party service. You can revoke access to any connected
        service at any time from your Settings page.
      </p>

      <h3>Technical Information</h3>
      <p>
        We collect standard server logs including IP address, browser type, operating system,
        access times, and pages viewed. We also collect error logs to diagnose and fix issues
        with the Service.
      </p>

      <h2>How We Use Your Information</h2>
      <ul>
        <li>To provide, maintain, and improve the Service</li>
        <li>To process and execute your requests through connected tools</li>
        <li>To communicate with you about your account, updates, or security notices</li>
        <li>To detect, prevent, and address technical issues, fraud, or abuse</li>
        <li>To comply with legal obligations</li>
      </ul>

      <h2>Data Storage and Security</h2>
      <p>
        Your data is stored in encrypted PostgreSQL databases hosted in the European Union
        (EU). All data is encrypted in transit using TLS 1.3 and at rest using AES-256.
        OAuth tokens are additionally encrypted with a separate key before being stored.
      </p>
      <p>
        Code execution is performed in isolated, ephemeral sandbox environments that are
        destroyed immediately after task completion. No user data persists in these environments.
      </p>

      <h2>Third-Party Services</h2>
      <p>
        EthioClaw connects to third-party services solely at your direction. When you authorize
        a connection, the third party&rsquo;s privacy policy governs their handling of your data.
        We encourage you to review the privacy policies of any services you connect.
      </p>
      <p>
        We do not sell your personal information to third parties. We do not use your
        conversation data to train AI models without your explicit consent.
      </p>

      <h2>Your Rights</h2>
      <p>
        Depending on your jurisdiction, you may have the right to:
      </p>
      <ul>
        <li>Access the personal data we hold about you</li>
        <li>Request correction of inaccurate data</li>
        <li>Request deletion of your account and associated data</li>
        <li>Withdraw consent for data processing (where applicable)</li>
        <li>Export your data in a machine-readable format</li>
        <li>Lodge a complaint with a supervisory authority</li>
      </ul>
      <p>
        To exercise any of these rights, contact us at the email address listed at the bottom
        of this policy.
      </p>

      <h2>Data Retention</h2>
      <p>
        We retain your account data and conversation history for as long as your account is
        active. If you delete your account, we will remove your personal data from our active
        systems within 30 days. Anonymized usage statistics may be retained for analytical
        purposes.
      </p>

      <h2>Children&rsquo;s Privacy</h2>
      <p>
        The Service is not intended for use by individuals under the age of 16. We do not
        knowingly collect personal information from children under 16. If you believe we have
        collected such information, please contact us immediately.
      </p>

      <h2>Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify you of any
        material changes by posting the new policy on this page and updating the
        &ldquo;Last updated&rdquo; date. Continued use of the Service after changes constitutes
        acceptance of the updated policy.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, please contact us at{" "}
        <a href="mailto:privacy@ethioclaw.dev">privacy@ethioclaw.dev</a>.
      </p>
    </LegalLayout>
  );
}
